
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prog5db
    username: dma6m6
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8888
